# Generated by Django 3.1.5 on 2021-03-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='readable_by',
        ),
    ]
